---
channel ids:
email pattern: '(.+) p.+ (.+) in (.+)\n<(.+)>.\n\n(?:\[.*\n)?(?:Due: (.+)\n(.+)\n)?([\s\S]+)\nO.+[\n ]<(.+)>'
email query: from:(classroom.google.com) newer_than:1d
refresh interval: 60
